# frozen_string_literal: true

source "https://rubygems.org"

gem "sinatra" , ">= 4.2.0" # web app
gem 'pry' # debugger
gem 'nokogiri' # xml parsing
gem 'aws-sdk-appconfigdata'
gem 'rackup', '>= 2.2.0'